Ad Reporting V2 Updates
fivetran/dbt_facebook_ads_source pull request #22
Opened 2022-06-22 22:00 UTC by fivetran-sheringuyen

Pull Request
**Are you a current Fivetran customer?** 
Fivetran created

**What change(s) does this PR introduce?** 

- Updates source models to include more potentially useful columns
- Updates `is_most_recent_record` logic to take in `updated_time` where the field is available in history tables including: campaign, ad_set and ad
- Updates respective `.yml` files for newly added columns
- Applies `README` updates for new formatting
- Enables use of identifiers to all source models

**Did you update the CHANGELOG?** 

- [ ] Yes

**Does this PR introduce a breaking change?**

- [x] Yes (please provide breaking change details below.)
- [ ] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [ ] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [x] No 

**How did you test the PR changes?** 

 

- [x] CircleCi  
- [x] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [x] BigQuery
- [x] Redshift
- [x] Snowflake
- [x] Postgres
- [x] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2022-06-27 21:17 UTC, fivetran-joemarkiewicz requested changes
@fivetran-sheringuyen thank you for opening this PR and putting a lot of effort into understanding the nuances of the Facebook Ads platform! This overall looks great, I do have a few comments to be addressed before this will be good to approve:

- [ ] Address the inline comments and suggestions within this PR

2022-06-28 17:40 UTC, fivetran-sheringuyen commented on integration_tests/seeds/facebook_ads_ad_history_data.csv
> +id,account_id,ad_set_id,campaign_id,creative_id,name,updated_time
Oh good call out! I meant to test this to see if it would pass the integration tests and then swap out the data - I'll do that now.

2022-06-28 18:10 UTC, fivetran-sheringuyen commented on models/stg_facebook_ads.yml
> +            - _fivetran_synced
I spoke to Drew about it - these are known missing fields from the FB data specifically only ad history, ad_set history and campaign history have updated_time while for some reason FB does not provide this same field for account and creative. I think updated_time is a more accurate way of calculating the latest record while _fivetran_synced is actually used as a proxy for tables that do not provide updated_time.

2022-06-28 18:12 UTC, fivetran-sheringuyen commented on models/stg_facebook_ads.yml
> +        description: "{{ doc('_fivetran_synced') }}"
I will add them back into the staging model!

2022-06-28 19:20 UTC, fivetran-sheringuyen commented
Howdy @fivetran-joemarkiewicz ! Just updated with the fixes and resolved the fixed convos. Let me know if there's anything else you want to discuss!

2022-06-29 15:15 UTC, fivetran-joemarkiewicz commented on models/stg_facebook_ads.yml
> +            - _fivetran_synced
Thanks for this context @fivetran-sheringuyen and this sounds good. Thanks!

2022-07-20 17:12 UTC, fivetran-sheringuyen commented
Running comments before merge:
- Add not_null testing in stg tests

2022-09-01 22:00 UTC, merged